config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tournaments#index'

  resources :tournaments, only: %i[index show new create] do
    resources :categories, controller: 'tournaments/categories' do
      resources :fighters, controller: 'tournaments/categories/fighters'
    end
    resources :academies, controller: 'tournaments/academies' do
      resources :fighters, controller: 'tournaments/academies/fighters'
    end
    resources :categories_fights, controller: 'tournaments/categories_fights' do
      resources :fights, controller: 'tournaments/categories_fights/fights'
    end
  end

  resources :academies
end

app/models/academy.rb
class Academy < ApplicationRecord
  has_many :registrations
  has_many :tournaments, through: :registrations
  has_many :fighters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  LEVELS_LIST = %i[BASICO INTERMEDIO AVANZADO].freeze
  
  has_many :tournaments_categories
  has_many :tournaments, through: :tournaments_categories
  has_many :fighters
  has_many :fights
  has_many :rounds

  validate :min_weight_per_level

  default_scope { order(min_weight: :asc) }

  scope :by_level, ->(level) { where(level: level) }
  scope :set, ->(weight) { where("max_weight >= #{weight} AND min_weight <= #{weight}") }

  def name
    if min_weight < 90
      "#{min_weight} - #{max_weight}"
    else
      'PESO COMPLETO'
    end
  end

  private

  def min_weight_per_level
    return unless Category.all.exists?(level: level, min_weight: min_weight)

    errors[:level] << 'Peso y nivel ya existen'
  end
end

app/models/fight.rb
class Fight < ApplicationRecord
  belongs_to :category
  belongs_to :tournament
  belongs_to :round
  has_many :fights_fighters
  has_many :fighters, through: :fights_fighters

  validate :one_fight_per_fighters

  private

  def one_fight_per_fighters
    return unless Fight.joins(:fighters).exists?(fighters: fighters.first)

    errors[:fighters] << 'Fight exists'
  end
end

app/models/fighter.rb
class Fighter < ApplicationRecord
  belongs_to :level
  belongs_to :academy
  belongs_to :category
  has_many :fights_fighters
  has_many :fights, through: :fights_fighters

  scope :by_tournament, lambda { |tournament|
    joins(:fights).where(fights: { tournament: tournament })
  }
end

app/models/fights_fighter.rb
class FightsFighter < ApplicationRecord
  belongs_to :fight
  belongs_to :fighter
end

app/models/level.rb
class Level < ApplicationRecord
  LEVELS_LIST = %i[BASICO INTERMEDIO AVANZADO].freeze
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :tournament
  belongs_to :academy
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :category
  has_many :fights
end

app/models/signed_in.rb
class SignedIn < ApplicationRecord
  belongs_to :fighter
  belongs_to :tournament
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :registrations
  has_many :academies, through: :registrations
  has_many :tournaments_categories
  has_many :categories, through: :tournaments_categories
  has_many :fights
end

app/models/tournaments_category.rb
class TournamentsCategory < ApplicationRecord
  belongs_to :tournament
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tournaments/academies/fighters_controller.rb
module Tournaments
  module Academies
    class FightersController < ApplicationController
      before_action :set_variables

      def new
        @fighter = Fighter.new
      end

      def create
        @fighter = ::Tournaments::Academies::Fighters::Create.new(params: fighter_params,
                                                                  academy: @academy,
                                                                  tournament: @tournament).call!

        if @fighter.save!
          redirect_to tournament_academy_path(@tournament, @academy)
        else
          render :new
        end
      end

      private

      def fighter_params
        params.require(:fighter).permit(%i[age name document weight level_id])
      end

      def set_variables
        @tournament = Tournament.find(params[:tournament_id])
        @academy = Academy.find(params[:academy_id])
      end
    end
  end
end

app/controllers/tournaments/academies_controller.rb
module Tournaments
  class AcademiesController < ApplicationController
    before_action :set_tournament

    def show
      @academy = Academy.find(params[:id])
    end

    def new
      @academy = Academy.new
    end

    def create
      @academy = Academy.new(academy_params.merge(tournaments: [@tournament]))

      if @academy.save
        redirect_to tournament_academy_path(@tournament, @academy)
      else
        render :new
      end
    end

    private

    def academy_params
      params.require(:academy).permit(:name)
    end

    def set_tournament
      @tournament = Tournament.find(params[:tournament_id])
    end
  end
end

app/controllers/tournaments/categories_controller.rb
module Tournaments
  class CategoriesController < ApplicationController
    before_action :set_tournament

    def index
      @category = @tournament.categories
    end

    def show
      @category = Category.find(params[:id])
    end

    private

    def set_tournament
      @tournament = Tournament.find(params[:tournament_id])
    end
  end
end

app/controllers/tournaments/categories_fights_controller.rb
module Tournaments
  class CategoriesFightsController < ApplicationController
    before_action :set_tournament

    def index
      ::Tournaments::Fights::Set.new(tournament: @tournament).call! unless @tournament.fights.exists?
    end

    def show
      @category = Category.find(params[:id])
    end

    private

    def set_tournament
      @tournament = Tournament.find(params[:tournament_id])
    end
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def index
    @tournaments = Tournament.all
  end

  def show
    @tournament = Tournament.find(params[:id])
  end

  def new
    @tournament = Tournament.new
  end

  def create
    @tournament = Tournament.new(tournament_params)

    if @tournament.save
      redirect_to @tournament
    else
      render :new
    end
  end

  private

  def tournament_params
    params.require(:tournament).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tournaments/academies_helper.rb
module Tournaments::AcademiesHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/academies/fighters/new.html.haml
= render partial: '/shared/titles',
  locals: { links: [{ name: 'TORNEO ACTUAL', path: tournament_path(@tournament) },
                    { name: @academy.name.upcase, path: tournament_academy_path(@tournament, @academy)}],
  title: "AGREGAR PELEADOR DE LA ESCUELA #{@academy.name.upcase}" }
= form_with model: [@tournament, @academy, @fighter], local: true do |f|
  .field
    = f.label :name, 'NOMBRE DEL PELEADOR', class: 'label'
    %p.control
      = f.text_field :name, class: 'input', placeholder: 'Nombre del peleador. Ejemplo: JUAN PEREZ', autofocus: true
  .field
    = f.label :document, 'CEDULA DEL PELEADOR', class: 'label'
    %p.control
      = f.number_field :document, class: 'input', placeholder: 'NRO de cedula del peleador. Ejemplo: 22222222'
  .field
    = f.label :age, 'EDAD DEL PELEADOR', class: 'label'
    %p.control
      = f.number_field :age, class: 'input', placeholder: 'Edad del peleador. Ejemplo: 22'
  .field
    = f.label :weight, 'PESO DEL PELEADOR', class: 'label'
    %p.control
      = f.number_field :weight, class: 'input', placeholder: 'Peso del peleador. Ejemplo: 85'
  .field
    = f.label :level, 'NIVEL DEL PELEADOR', class: 'label'
    %p.select.is-fullwidth
      = f.select :level_id, Category::LEVELS_LIST.collect{ |l| [l] }, 
        { prompt: 'Seleccionar el nivel en el que se encuentra el peleador' }
  .field
    %strong= f.submit 'GUARDAR', class: 'button is-rounded is-blue'

app/views/tournaments/academies/new.html.haml
= render partial: '/shared/titles',
  locals: { links: [{ name: 'TORNEO ACTUAL', path: tournament_path(@tournament) }],
  title: "AGREGAR ESCUELA PARTICIPANTE EN #{@tournament.name.upcase}" }
%hr/
= form_with model: [@tournament, @academy], local: true do |f|
  .field
    = f.label :name, 'INGRESAR EL NOMBRE DE LA ESCUELA', class: 'label'
    %p.control
      = f.text_field :name, class: 'input', autofocus: true
  .field
    %strong= f.submit 'AGREGAR', class: 'button is-rounded is-blue'

app/views/tournaments/academies/show.html.haml
= render partial: '/shared/titles',
  locals: { links: [{ name: 'TORNEO ACTUAL', path: tournament_path(@tournament) }],
  title: @academy.name.upcase }
%hr
.title.is-4 LISTA DE PELEADORES
%table.table.is-fullwidth
  %thead
    %th NOMBRE
    %th EDAD
    %th CEDULA
    %th PESO
    %th CATEGORIA
    %th NIVEL
  %tbody
    - @academy.fighters.each do |f|
      %tr
        %td= f.name.titleize
        %td= f.age
        %td= f.document
        %td= f.weight
        %td= "#{f.category.max_weight < 100 ? "#{f.category.min_weight} - #{f.category.max_weight}" : 'Peso Completo'}"
        %td= f.level.name
    - unless @academy.fighters.exists?
      %tr
        %th.has-text-centered{colspan: 6} NO SE HAN AGREGADO PELEADORES
    %tr
      %th.has-text-centered{colspan: 6}
        = link_to 'AGREGAR PELEADOR', new_tournament_academy_fighter_path(@tournament, @academy), class: 'button is-rounded is-yellow'

app/views/tournaments/categories/index.html.haml
= render partial: '/shared/titles',
  locals: { links: [{ name: 'TORNEO ACTUAL', path: tournament_path(@tournament) }],
  title: "LISTA DE CATEGORIAS" }
%table.table.is-fullwidth
  %thead
    %tr
      %th PESO MINIMO
      %th PESO MAXIMO
      %th CANTIDAD DE PELEADORES
      %th CANTIDAD DE PELEAS
      %th TORNEOS
      %th
  %tbody
    - @category.each do |c|
      %tr
        - if c.max_weight > 91
          %th.has-text-centered{colspan: 2} PESO COMPLETO
        - else
          %td= c.min_weight
          %td= c.max_weight
        %td= c.fighters.count
        %td= c.fights.count
        %td= c.tournaments.count
        %th= link_to 'VER DETALLES', tournament_category_path(@tournament, c), class: 'button is-rounded is-small is-black'

app/views/tournaments/categories/show.html.haml
- category = "#{@category.min_weight < 90 ? "#{@category.min_weight}KG - #{@category.max_weight}KG" : 'PESO COMPLETO'}"
= render partial: '/shared/titles',
  locals: { links: [{ name: 'TORNEO ACTUAL', path: tournament_path(@tournament) },
                    {name: 'LISTA DE CATEGORIAS', path: tournament_categories_path(@tournament, @category)}],
  title: "LISTA DE PELEADORES EN LA CATEGORIA #{category} #{@category.level}" }
%table.table.is-fullwidth
  %thead
    %tr
      %th NOMBRE
      %th EDAD
      %th PESO
      %th DOCUMENTO
      %th ESCUELA
      %th
  %tbody
    - @category.fighters.each do |f|
      %tr
        %td= f.name
        %td= f.age
        %td= f.weight
        %td= f.document
        %th= link_to f.academy.name, academy_path(f.academy), class: 'has-text-blue'
        %th= link_to 'VER DETALLES', tournament_category_fighters_path(@tournament, @category, f), 
              class: 'button is-rounded is-small is-black'

app/views/tournaments/categories_fights/index.html.haml
= render partial: '/shared/titles', locals: { title: "Peleas de #{@tournament.name.upcase}",
  links: [{ name: 'TORNEO ACTUAL', path: tournament_path(@tournament) }] }
%table.table.is-fullwidth
  %thead
    %tr
      %th CATEGORIA
      %th NRO DE PELEADORES
      %th NIVEL
      %th NRO DE PELEAS
      %th NRO DE RONDAS
      %th
  %tbody
    - @tournament.categories.each do |c|
      %tr
        %td= "#{c.min_weight < 90 ? "#{c.min_weight} - #{c.max_weight}" : "PESO COMPLETO"}"
        %td= c.fighters.count
        %td= c.level
        %td= c.fights.count
        %td= c.rounds.count
        %td= link_to 'VER DETALLES', tournament_categories_fight_path(@tournament, c),
              class: 'button is-small is-rounded is-black'

%h1 2013 NCAA Tournament - Midwest Bracket
%main#tournament
  %ul.round.round-1
    %li.spacer  
    %li.game.game-top.winner
      Lousville
      %span 79
    %li.game.game-spacer  
    %li.game.game-bottom
      NC A&T
      %span 48
    %li.spacer  
    %li.game.game-top.winner
      Colo St
      %span 84
    %li.game.game-spacer  
    %li.game.game-bottom
      Missouri
      %span 72
    %li.spacer  
    %li.game.game-top
      Oklahoma St
      %span 55
    %li.game.game-spacer  
    %li.game.game-bottom.winner
      Oregon
      %span 68
    %li.spacer  
    %li.game.game-top.winner
      Saint Louis
      %span 64
    %li.game.game-spacer  
    %li.game.game-bottom
      New Mexico St
      %span 44
    %li.spacer  
    %li.game.game-top.winner
      Memphis
      %span 54
    %li.game.game-spacer  
    %li.game.game-bottom
      St Mary's
      %span 52
    %li.spacer  
    %li.game.game-top.winner
      Mich St
      %span 65
    %li.game.game-spacer  
    %li.game.game-bottom
      Valparaiso
      %span 54
    %li.spacer  
    %li.game.game-top.winner
      Creighton
      %span 67
    %li.game.game-spacer  
    %li.game.game-bottom
      Cincinnati
      %span 63
    %li.spacer  
    %li.game.game-top.winner
      Duke
      %span 73
    %li.game.game-spacer  
    %li.game.game-bottom
      Albany
      %span 61
    %li.spacer  
  %ul.round.round-2
    %li.spacer  
    %li.game.game-top.winner
      Lousville
      %span 82
    %li.game.game-spacer  
    %li.game.game-bottom
      Colo St
      %span 56
    %li.spacer  
    %li.game.game-top.winner
      Oregon
      %span 74
    %li.game.game-spacer  
    %li.game.game-bottom
      Saint Louis
      %span 57
    %li.spacer  
    %li.game.game-top
      Memphis
      %span 48
    %li.game.game-spacer  
    %li.game.game-bottom.winner
      Mich St
      %span 70
    %li.spacer  
    %li.game.game-top
      Creighton
      %span 50
    %li.game.game-spacer  
    %li.game.game-bottom.winner
      Duke
      %span 66
    %li.spacer  
  %ul.round.round-3
    %li.spacer  
    %li.game.game-top.winner
      Lousville
      %span 77
    %li.game.game-spacer  
    %li.game.game-bottom
      Oregon
      %span 69
    %li.spacer  
    %li.game.game-top
      Mich St
      %span 61
    %li.game.game-spacer  
    %li.game.game-bottom.winner
      Duke
      %span 71
    %li.spacer  
  %ul.round.round-4
    %li.spacer  
    %li.game.game-top.winner
      Lousville
      %span 85
    %li.game.game-spacer  
    %li.game.game-bottom
      Duke
      %span 63
    %li.spacer  

app/views/tournaments/categories_fights/show.html.haml
= render partial: '/shared/titles', 
  locals: { title: "PELEAS EN LA CATEGORIA #{@category.name}",
  links: [{ name: 'TORNEO ACTUAL', path: tournament_path(@tournament) },
          { name: 'LISTA DE CATEGORIAS', path: tournament_categories_fights_path(@tournament) }] }
%main#tournament
  - @category.rounds.each do |r|
    %ul{ class: "round round-#{r.number}" }
      - r.fights.each do |fight|
        = link_to tournament_categories_fight_fight_path(@tournament , @category, fight),
          class: 'has-text-blue' do
          - fight.fighters.each do |f|
            %li{ class: "#{f == fight.fighters.first ? 'spacer' : 'game game-spacer'}" }
            %li{ class: "game game-#{f == fight.fighters.first ? 'top' : 'bottom'} 
                         #{f.winner? ? 'winner' : ''}" }
              %p
                = "#{f.name.upcase}"
                %span.has-text-weight-bold= "#{f.weight}KG"

app/views/tournaments/index.html.haml
.title.has-text-centered BIENVENIDO SELECCIONA UN TORNEO
.has-text-centered= link_to 'AGREGAR TORNEO', new_tournament_path, class: 'button is-rounded is-blue'
%hr/
%table.table.is-fullwidth
  %thead
    %tr
      %th NOMBRE
      %th FECHA
      %th 
  %tbody
    - @tournaments.each do |t|
      %tr
        %td= t.name
        %td= t.created_at.strftime('%d/%m/%Y %I:%M %p')
        %td= link_to 'VER DETALLE', tournament_path(t), class: 'button is-rounded is-small is-black'
    - unless @tournaments.exists?
      %tr
        %th.has-text-centered{ colspan: 3 } NO EXISTEN TORNEOS AGREGADOS

app/views/tournaments/new.html.haml
.title.has-text-centered BIENVENIDO ¿DESEAS AGREGAR UN NUEVO TORNEO?
%hr/
= form_with model: @tournament, local: true do |f|
  .field
    = f.label :name, 'INGRESAR EL NOMBRE DEL TORNEO', class: 'label'
    %p.control
      = f.text_field :name, class: 'input', autofocus: true
  .field
    = f.submit 'AGREGAR', class: 'button is-rounded is-blue'

app/views/tournaments/show.html.haml
.title.has-text-centered
  = @tournament.name.titleize
  %strong.help
    REALIZADO:
    = @tournament.created_at.strftime('%d/%m/%Y %I:%M %p')
%hr/
.columns
  .column
    .title.is-4 ESCUELAS INSCRITAS
    %table.table.is-fullwidth
      %thead
        %tr 
          %th NOMBRE
          %th NRO. ESTUDIANTES
          %th
      %tbody
        - @tournament.academies.each do |a|
          %tr
            %td= a.name.titleize
            %td= a.fighters.count
            %th= link_to 'VER DETALLE', tournament_academy_path(@tournament, a), class: 'button is-small is-rounded is-black'
        - unless @tournament.academies.exists?
          %tr
            %th.has-text-centered{colspan: 3} NO HAY ESCUELAS INSCRITAS
        %tr
          %th.has-text-centered{colspan: 3}
            = link_to 'AGREGAR ESCUELA', new_tournament_academy_path(@tournament), class: 'button is-rounded is-blue'
  .column
    .title.is-4 CATEGORIAS INSCRITAS
    %table.table.is-fullwidth
      %thead
        %tr
          %th PESO MIN.
          %th PESO MAX.
          %th NIVEL
          %th PELEADORES
          %th
      %tbody
        - @tournament.categories.each do |c|
          %tr
            - if c.max_weight > 91
              %th.has-text-centered{colspan: 2} PESO COMPLETO
              %td= c.level
            - else
              %td= c.min_weight
              %td= c.max_weight
              %td= c.level
            %td= c.fighters.count
            %th= link_to 'VER DETALLES', tournament_category_path(@tournament, c), class: 'button is-rounded is-small is-black'
        - unless @tournament.categories.exists?
          %tr
            %th.has-text-centered{colspan: 4} NO HAY CATEGORIAS CON PELEADORES INSCRITOS
        %tr
          %th.has-text-centered{ colspan: 4 }
            = link_to 'VER CATEGORIAS', tournament_categories_path(@tournament), class: 'button is-rounded is-yellow'
%hr
.has-text-centered
  %strong= link_to 'VER PELEAS', tournament_categories_fights_path(@tournament), class: 'button is-rounded is-red'